name: "Check Files Action"
description: "Checks if Readme and License are present"
runs:
  using: node16
  main: index.js
inputs:
  repo-token:
    type: string
    description: "github Personal Access Token"
    required: true
    default: ${{ github.token }}